---
title: "HW5"
author: "Seonyoung Park (sp3804)"
date: "11/10/2020"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
library(rvest)

```

```{r}
homicide_df = read.csv("homicide-data.csv")

```

```{r}

homicide_df = homicide_df %>%
  mutate(
    city_state=str_c(city,state, sep="_"),
    resolved=case_when(
      disposition=="Closed without arrest"~"unsolved",
      disposition=="Open/No arrest"~"unsolved",
      disposition=="Closed by arrest"~"solved",
    )
  )

```



```{r}
aggregate_df = 
  homicide_df %>%
  group_by(city_state) %>%
  summarise(
    hom_total = n(),
    hom_unsolved = sum(resolved == "unsolved")
  )

```


Can I do a prop test for a single city?

```{r}
prop.test(
  aggregate_df %>%filter(city_state == "Baltimore_MD") %>%pull(hom_unsolved),
  aggregate_df %>% filter(city_state=="Baltimore_MD")%>% pull(hom_total)) %>%
    broom::tidy()


```

Try to iterate...

```{r}
aggregate_df %>%
  mutate(
    prop_tests=map2(.x=hom_unsolved, .y=hom_total, ~prop.test(x=.x, n=.y)),
    tidy_tests=map(.x=prop_tests, ~broom::tidy(.x))
  ) %>%
  select(-prop_tests) %>%
  unnest(tidy_tests) %>%
  select(city_state, estimate, conf.low, conf.high)

````

## Problem 2 ideas....

```{r}
data_1=read_csv("lda_data/con_01.csv")

```

## Question 3
- set.seed() for reproducibility
- t.test against mu=0 (true population mean)

```{r}
path_df = 
  tibble(
    path=list.files("lda_data"),
  ) %>%
  muatate(
    path=str_c("lad_data/", path),
    data=map(.......))
  )

read_csv(path_df$path[[1]])

````




